### ISSUE TITLE
Make Compatible with Android 6.0 and Cyanogenmod 13

### ISSUE THREAD

**Issue by landry314** [C3C0/GravityBox#363]
Please...

**Comment by C3C0** [comment]
This is not the official repo (the official one is under Gravitybox organization), but anyway, I don't provide nor plan to provide compatibility with the custom Roms due to several reasons:
- custom Roms are typically built from source thus the best way is to implement features the standard way - at source code level. You can try to request features from the custom ROM devs.
- custom Roms are very dynamic and it wouldn't be manageable to keep track of changes that happen too frequently.
